services:
  rhymix:
    image: navystack/rhymix
    container_name: rhymix-dev
    restart: unless-stopped
    ports:
      - "4001:80"
      - "4443:443"
    volumes:
      - ./rhymix/www/html:/var/www/html
      - ./rhymix/nginx/conf.d/rhymix.conf:/etc/nginx/sites-available/default
      - ./rhymix/ssl:/etc/ssl/certs
      - ./rhymix/logs:/var/log/nginx
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80